name: US-01 Event Feed Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant permission
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest


#  instrumented-tests:
#    name: Run Emulator Tests
#    runs-on: macos-latest
#
#    steps:
#      - name: Checkout repo
#        uses: actions/checkout@v4
#
#      - name: Set up JDK
#        uses: actions/setup-java@v4
#        with:
#          distribution: temurin
#          java-version: 17
#
#      - name: Run emulator tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 30
#          arch: x86_64
#          profile: Nexus 6
#          script: ./gradlew connectedDebugAndroidTest